# Generated by Django 6.0.4 on 2026-04-20 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecoderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField(blank=True)),
                ('encoding_type', models.CharField(choices=[('base64', 'Base64'), ('url', 'URL Encode'), ('html', 'HTML Encode'), ('hex', 'Hex'), ('binary', 'Binary'), ('gzip', 'GZip')], max_length=20)),
                ('operation', models.CharField(choices=[('encode', 'Encode'), ('decode', 'Decode')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntruderPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attack_type', models.CharField(choices=[('sniper', 'Sniper'), ('battering_ram', 'Battering Ram'), ('pitchfork', 'Pitchfork'), ('cluster_bomb', 'Cluster Bomb')], default='sniper', max_length=20)),
                ('target_url', models.URLField(max_length=2048)),
                ('request_template', models.TextField()),
                ('payloads', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('OPTIONS', 'OPTIONS')], max_length=10)),
                ('url', models.URLField(max_length=2048)),
                ('host', models.CharField(max_length=255)),
                ('path', models.TextField()),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('response_length', models.IntegerField(default=0)),
                ('response_time', models.FloatField(default=0.0)),
                ('intercepted', models.BooleanField(default=False)),
                ('modified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepeaterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('url', models.URLField(max_length=2048)),
                ('headers', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True)),
                ('response_time', models.FloatField(default=0.0)),
                ('history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('paused', 'En pause')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('url', models.URLField(max_length=2048)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('request_data', models.TextField(blank=True)),
                ('response_data', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('confidence', models.CharField(default='Certain', max_length=50)),
                ('remediation', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mon_projet.scantarget')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='SpiderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('content_length', models.IntegerField(default=0)),
                ('parent_url', models.URLField(blank=True, max_length=2048)),
                ('forms_found', models.IntegerField(default=0)),
                ('links_found', models.IntegerField(default=0)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider_results', to='mon_projet.scantarget')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
    ]
