# Generated by Django 6.0 on 2026-05-14 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecoderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField(blank=True)),
                ('encoding_type', models.CharField(choices=[('base64', 'Base64'), ('url', 'URL'), ('html', 'HTML'), ('hex', 'Hex'), ('binary', 'Binary'), ('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256')], max_length=20)),
                ('operation', models.CharField(choices=[('encode', 'Encode'), ('decode', 'Decode'), ('hash', 'Hash')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntruderPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('attack_type', models.CharField(choices=[('sniper', 'Sniper'), ('battering_ram', 'Battering Ram'), ('pitchfork', 'Pitchfork'), ('cluster_bomb', 'Cluster Bomb')], default='sniper', max_length=20)),
                ('target_url', models.URLField(max_length=1000)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('headers', models.TextField(blank=True, default='{}')),
                ('body', models.TextField(blank=True)),
                ('payloads', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('results', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProxyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('url', models.URLField(max_length=1000)),
                ('headers', models.TextField(blank=True, default='{}')),
                ('body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, default='{}')),
                ('response_body', models.TextField(blank=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('intercepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RepeaterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('url', models.URLField(max_length=1000)),
                ('headers', models.TextField(blank=True, default='{}')),
                ('body', models.TextField(blank=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers', models.TextField(blank=True, default='{}')),
                ('response_body', models.TextField(blank=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_issues', models.IntegerField(default=0)),
                ('high_issues', models.IntegerField(default=0)),
                ('medium_issues', models.IntegerField(default=0)),
                ('low_issues', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpiderResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('links_found', models.IntegerField(default=0)),
                ('forms_found', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('xss', 'Cross-Site Scripting (XSS)'), ('sqli', 'SQL Injection'), ('csrf', 'CSRF'), ('open_redirect', 'Open Redirect'), ('missing_header', 'Missing Security Header'), ('info_disclosure', 'Information Disclosure'), ('ssl', 'SSL/TLS Issue'), ('clickjacking', 'Clickjacking')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('url', models.URLField(max_length=500)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('payload', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mon_projet.scantarget')),
            ],
            options={
                'ordering': ['-severity', 'issue_type'],
            },
        ),
        migrations.CreateModel(
            name='ScanIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('xss', 'Cross-Site Scripting (XSS)'), ('sqli', 'SQL Injection'), ('csrf', 'CSRF'), ('open_redirect', 'Open Redirect'), ('missing_header', 'Missing Security Header'), ('info_disclosure', 'Information Disclosure'), ('ssl', 'SSL/TLS Issue'), ('clickjacking', 'Clickjacking')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('payload', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='mon_projet.scantarget')),
            ],
            options={
                'ordering': ['-severity', 'issue_type'],
            },
        ),
    ]
