# Generated by Django 6.0 on 2026-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoderdata',
            options={},
        ),
        migrations.AlterModelOptions(
            name='intruderpayload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repeaterrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='spiderresult',
            options={},
        ),
        migrations.RenameField(
            model_name='scanresult',
            old_name='discovered_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='spiderresult',
            old_name='discovered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='intruderpayload',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='intruderpayload',
            name='method',
        ),
        migrations.RemoveField(
            model_name='intruderpayload',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='repeaterrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='spiderresult',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='spiderresult',
            name='forms_found',
        ),
        migrations.RemoveField(
            model_name='spiderresult',
            name='links_found',
        ),
        migrations.AlterField(
            model_name='decoderdata',
            name='encoding_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='decoderdata',
            name='operation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='decoderdata',
            name='output_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intruderpayload',
            name='attack_type',
            field=models.CharField(default='sniper', max_length=50),
        ),
        migrations.AlterField(
            model_name='intruderpayload',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='intruderpayload',
            name='results',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='intruderpayload',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='intruderpayload',
            name='target_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proxyrequest',
            name='headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proxyrequest',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='proxyrequest',
            name='response_headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proxyrequest',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='repeaterrequest',
            name='headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repeaterrequest',
            name='name',
            field=models.CharField(default='Request', max_length=255),
        ),
        migrations.AlterField(
            model_name='repeaterrequest',
            name='response_headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='repeaterrequest',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='issue_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='severity',
            field=models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Faible'), ('info', 'Info')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='scantarget',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spiderresult',
            name='status_code',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='spiderresult',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spiderresult',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.DeleteModel(
            name='ScanIssue',
        ),
    ]
